const String splashscreenRoute = '/SplashScreen';
const String loginScreenRoute= '/LoginScreen';
const String homeRoute= '/HomeScreen';
const String registerRoute= '/RegisterScreen';
const String welcomeRoute= '/WelcomeScreen';
const String supportRoute= '/SupportScreen';
const String profileRoute= '/ProfileScreen';
const String settingRoute= '/SettingScreen';
const String PackageDetailRoute= '/PackageDatailScreen';
